
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE FMT FUNC ID IMPORT LBRACE LPAREN MINUS NUMBER PACKAGE PERIOD PLUS PRINTLN RBRACE RPAREN SEMICOLON STRING TIMESprogram : PACKAGE ID SEMICOLON import_declaration function_declarationimport_declaration : IMPORT STRING SEMICOLONfunction_declaration : FUNC ID LPAREN RPAREN LBRACE statement RBRACEstatement : FMT PERIOD PRINTLN LPAREN STRING RPAREN'
    
_lr_action_items = {'PACKAGE':([0,],[2,]),'$end':([1,7,17,],[0,-1,-3,]),'ID':([2,8,],[3,10,]),'SEMICOLON':([3,9,],[4,11,]),'IMPORT':([4,],[6,]),'FUNC':([5,11,],[8,-2,]),'STRING':([6,20,],[9,21,]),'LPAREN':([10,19,],[12,20,]),'RPAREN':([12,21,],[13,22,]),'LBRACE':([13,],[14,]),'FMT':([14,],[16,]),'RBRACE':([15,22,],[17,-4,]),'PERIOD':([16,],[18,]),'PRINTLN':([18,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'import_declaration':([4,],[5,]),'function_declaration':([5,],[7,]),'statement':([14,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PACKAGE ID SEMICOLON import_declaration function_declaration','program',5,'p_program','main.py',87),
  ('import_declaration -> IMPORT STRING SEMICOLON','import_declaration',3,'p_import_declaration','main.py',92),
  ('function_declaration -> FUNC ID LPAREN RPAREN LBRACE statement RBRACE','function_declaration',7,'p_function_declaration','main.py',97),
  ('statement -> FMT PERIOD PRINTLN LPAREN STRING RPAREN','statement',6,'p_statement','main.py',102),
]
